### ISSUE TITLE
Clarify distinction between correlation-context and trace-context's tracestate

### ISSUE THREAD

**Issue by iredelmeier** [w3c/baggage#11]
We should clarify (first among ourselves, then in the spec) what use cases are appropriate for `correlation-context` vs `tracestate` (relates to #10).

There are probably some more distinctions we should make :)

**Comment by yurishkuro** [comment]
That's easy. `correlation-context` is for _user-provided_ context. `tracestate` is for tracer to store whatever it feels like.

**Comment by iredelmeier** [comment]
@yurishkuro to be clear, the ask is that we **document** the distinction.
