### ISSUE TITLE
Security and encryption considerations

### ISSUE THREAD

**Issue by remitly-srivatsa** [w3c/baggage#12]
The human readable requirement in this spec introduces security, privacy (PII etc.) considerations that should be called out. 

For example, [JWT](https://tools.ietf.org/html/rfc7519) provides an approach to communicate JSON based payload data usually via HTTP headers. And it also provides additional optional benefits such as signatures and encryption. Also, [ID Token](https://developers.google.com/identity/protocols/OpenIDConnect#authuser) is a means of encapsulating user identity in JWT Tokens.

Some information conveyed through contexts may either be sensitive or may be susceptible to tampering. It would be great to either:

- add signature/encryption as standard offerings when conveying correlation context
- and/or provide guidance on how to deal with security or encryption (for example, values could be JWT tokens)
- and/or call it as out of scope for this specification

**Comment by yurishkuro** [comment]
+1 to call it as out of scope. Not because this question is not important, but because this whole paradigm of passing application-specific data as baggage in all the requests is a pretty new concept, and I feel it's premature to be locking down values must be interpreted or represented.

**Comment by danielkhan** [comment]
We will provide PII/privacy/security wording to the spec but won't enforce a specific mechanism within the header.
