### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by basti1302** [w3c/baggage#122]
As we are approaching CR for this spec, we should acknowledge people that have contributed significantly to this spec, similar to https://www.w3.org/TR/trace-context/#acknowledgments.

This will be simple list of names in the form of: 
> Thanks to ${list of names} for their contributions to this work.

**Note: No one will be mentioned without having provided explicit consent to being mentioned.** If you are fine with being listed in the acknowledgements section, please confirm yourself in the list. 

Just from doing a bit of simple statistics via `git shortlog --summary --numbered --email`, I think the following people should be credited (alphabetical order). 

* [ ] Adrian Cole @codefromthecrypt
* [x] Armin Ruech @arminru 
* [ ] Bogdan Drutu @bogdandrutu 
* [ ] Philippe Le Hegaret @plehegar 
* [x] Reiley Yang @reyang 
* [x] Jonathan Mace @JonathanMace

This is very probably not a complete list. If you can think of someone else that should get credited, please comment. That also includes non-code contributions, which I have completely missed when compiling this list.

cc @SergeyKanzhelev just FYI

**Comment by basti1302** [comment]
I suggest we leave this open for some days/weeks, then I'll create a PR based on the outcome.

**Comment by reyang** [comment]
I confirm.

**Comment by kalyanaj** [comment]
Jonathan Mace contributed to the initial baggage concepts that preceded the w3c spec, so you may want to add him as well.

**Comment by basti1302** [comment]
@JonathanMace Do you consent to being mentioned in the acknowledgement section of the W3C baggage specification, as you came up with the idea originally? (Context: some people that have contributed to W3C working groups in the past do no longer want to be associated with it any longer for various reasons, so we now always ask for consent before crediting someone).

**Comment by JonathanMace** [comment]
Sure thing, I appreciate the mention!
