### ISSUE TITLE
Add rationale for why libraries MAY propagate or otherwise change to MUST

### ISSUE THREAD

**Issue by anuraaga** [w3c/baggage#25]
In the overview, the spec states `Libraries and platforms MAY propagate this header.`. It also says `This is a companion header for the traceparent.`

In the [spec](https://w3c.github.io/trace-context/#design-overview) for traceparent. `At a minimum they MUST propagate the traceparent and tracestate headers`.

So intuitively, it seems that if it's a companion to traceparent, and that MUST be propagated, this MUST be too and I'm confused why correlationcontext suggest it MAY propagate.

**Comment by dyladan** [comment]
I think we should probably just remove the wording that states this is a companion to traceparent. It solves an entirely different problem and could be propagated with or without trace context.

**Comment by justinfoote** [comment]
I agree.  They're two separate things, with mostly non-overlapping use cases.  

But even if we don't remove the line about correlation context being a companion to traceparent, this doesn't feel too inconsistent to me.  Some parts of the spec are mandatory (traceparent and tracestate), and some parts of the spec are optional (correlation context).

**Comment by adriancole** [comment]
Thanks @anuraaga the spec you mentioned is the only reason why brave's impl is nonsensically dropping good data in tracestate when traceparent doesn't exist.

To carry B3 (in tracestate) without traceparent is much easier than with it as the traceparent header, especially how it defines sampled is of no use except ID correlation. We have to ignore it basically.

**Comment by anuraaga** [comment]
It's an interesting point about keeping tracestate even if parent gets lost to at least have something to work with. 

It feels like that also fits the MUST propagate model well - header in, header out should generally give more functionality to users. 

I guess I'm still not clear on, is this one of the larger bucket of w3c trace header, so it's an optional feature (leaving it up to the user to manage libraries to get the features they need)? Or is it an independent feature. The replies give me both impressions. If it is an independent feature, surely we want that to mandate propagation so context parameters don't get lost?

**Comment by dyladan** [comment]
I see correlation context as a separate feature from trace context.

@adriancole if we allow propagation of tracestate without traceparent, that would violate what I view as one of the most important parts of the trace context spec which is interoperability between tracing systems. If one implementation only needs tracestate and doesn't create a traceparent, they are potentially breaking the traces of other systems.

In any case, I don't think that should apply to correlation context, which should be allowed to be propagated without a trace context.

**Comment by danielkhan** [comment]
We will remove `traceparent` wording and change to SHOULD
