### ISSUE TITLE
Review / update rationale

### ISSUE THREAD

**Issue by danielkhan** [w3c/baggage#26]
In https://github.com/w3c/correlation-context/pull/20/ @yurishkuro raised some concerns around the clarity/reasoning of some points in the rationale.
While we move ahead with the added normative wording that was the scope of the PR, this issue serves as tracking issue to review the rationale.

**Comment by yurishkuro** [comment]
Looks like the only unresolved was https://github.com/w3c/baggage/pull/20#discussion_r399450278, but I think it's not important.
