### ISSUE TITLE
Clarify if values are allowed to contain `=`

### ISSUE THREAD

**Issue by arminru** [w3c/baggage#34]
From the current syntax definition, values would be allowed to contain `=`:

https://github.com/w3c/baggage/blob/0573bd79c0d93a779145fd26a7b3e532c912c783/baggage/HTTP_HEADER_FORMAT.md#L27-L30

This way, `prop1=foo1=bar1;prop2=foo2=bar2,propX=fooX=barX`, for example, would be valid content.
Is this intended and were implications considered? The grammar is still unambiguous since comma and semicolon are not allowed for values but I'd still call this out at least in the examples to make consumers aware of it. Implementers might otherwise end up writing something like `string[] parsed = "prop1=foo1=bar1".split('='); key = parsed[0]; value = parsed[1]`.

**Comment by dyladan** [comment]
@arminru the value format was borrowed from the set-cookie header, which also allows `=`. `=` is also important as the padding character for base64 encoded values.

**Comment by arminru** [comment]
Makes sense!
I think we should make this more obvious for readers by either mentioning it or at least showing it in an example.
