### ISSUE TITLE
CfC: Move to First Public Working Draft

### ISSUE THREAD

**Issue by danielkhan** [w3c/baggage#36]
This specification reached a state where it is safe to mark it as [First Public Working Draft](https://www.w3.org/2017/Process-20170301/#working-draft).

A FPWD is a preliminary version of a spec and there are no requirements for completeness.

Following [the timeline](https://w3c.github.io/spec-releases/milestones/?fpwd=2020-10-13) the change would be made by October 13th, if we reach consensus.

**Comment by yurishkuro** [comment]
I opened a couple of minor PRs, but otherwise +1 to advance the status.

**Comment by mtwo** [comment]
I'm opening a PR with grammar nits, and I +1 to advance the status.

**Comment by dyladan** [comment]
+1 to advance, but I believe we still need to decide if order must be preserved

**Comment by danielkhan** [comment]
@caribouW3 we are good to go. What do we have to do next?

**Comment by caribouW3** [comment]
We can go ahead with publication, after updating respec.
