### ISSUE TITLE
Do name-value pair limits include the equals sign?

### ISSUE THREAD

**Issue by anuraaga** [w3c/baggage#51]
I think it's not clear what the limits precisely mean

https://w3c.github.io/baggage/#limits

It uses the term name-value pair which I don't think is actually defined in the doc. Most importantly I'm wondering if the equals sign is taken into consideration in the limits. Also for the "total length" limit, it would help to clarify whether comma is taken into consideration too.

**Comment by dyladan** [comment]
ABNF refers to it as `list-member` which does contain the `=`. I'll update the prose to use the ABNF naming. The total length should be the byte-length of the ABNF `list` which does contain the commas and OWS.

OWS is also being removed as an unrelated issue.
