### ISSUE TITLE
Publish FPWD

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/baggage#75]
Follow up from https://github.com/w3c/baggage/pull/73#discussion_r675245177. Let's publish FPWD since the editors list update that was blocking us was updated. @plehegar can you help?

**Comment by plehegar** [comment]
sorry for not catching this earlier. request sent. should be published on August 17 if accepted.

**Comment by plehegar** [comment]
euh... make it August 19. I got approval.

**Comment by plehegar** [comment]
I got confused somehow. The document is published in /TR already...

For example:
https://www.w3.org/TR/2021/WD-baggage-20210803/

**Comment by kalyanaj** [comment]
As the FPWD is live at https://www.w3.org/TR/baggage/, closing this issue, please re-activate if there's anything more required for this issue.
