### ISSUE TITLE
Baggage value clarification for parsing

### ISSUE THREAD

**Issue by lonewolf3739** [w3c/baggage#77]
[Baggage value difinition](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT.md#value)
> A value contains a URL encoded UTF-8 string. Leading and trailing whitespaces (OWS) are allowed but MUST be trimmed when converting the header into a data structure.
>
>Note, value MAY contain any number of the equal sign (=) characters. Parsers MUST NOT assume that the equal sign is only used to separate key and value.

If value is utf-8 URL encoded, isn't it redundant to say that parsers must not assume there are more than one equal sign?

**Comment by dyladan** [comment]
>If value is utf-8 URL encoded, isn't it redundant to say that parsers must not assume there are more than one equal sign?

It doesn't say parsers must not assume there is _more than one_ equal sign. It says they must not assume there is _only one_ equal sign. In any case, yes that is technically redundant. It is simply a warning that the naive parse like this will not work:

```javascript
const parts = header.split(',');
const entries = parts.map(e => e.split('=')); // this is broken because values may contain `=`
```
