### ISSUE TITLE
Need to have concrete ABNF syntax

### ISSUE THREAD

**Issue by reyang** [w3c/baggage#8]
We need to define the header format using ABNF, as what we've done for tracecontext https://github.com/w3c/trace-context/blob/master/spec/20-http_header_format.md#field-value

**Comment by reyang** [comment]
@SergeyKanzhelev I can work on the ABNF if you need my help.

**Comment by lmolkova** [comment]
More to this: spec suggest that correlation context is Url encoded string.

It means that all separator allowed by HTTP spec in header value will be escaped including separators spec defines (. `,`, `;`  and `=`):
e.g. 
`name1=value1;properties1,name2=value2;properties2` looks like `name1%3Dvalue1%3Bproperties1%2Cname2%3Dvalue2%3Bproperties2`

Besides being not readable, it also seems to break comma-separated multiple header fields behavior defined by HTTP.

We can say that keys, values, and properties have to be url encoded separately or find other ways to keep correlation-context values compliant with HTTP header values.

**Comment by yurishkuro** [comment]
@lmolkova your comment is already addressed (doesn't really belong to this issue).

Otherwise the format is already defined via ABNF, so closing this issue.
